### ISSUE TITLE
Add a function to measure vector states directly

### ISSUE THREAD

**Issue by nunezco2** [nunezco2/quAPL#23]

**Comment by marcosfrenkel** [comment]
What do you mean by this? measuring the whole of the vector state at once? if that is the case there is the measure function that does that already.

**Comment by nunezco2** [comment]
By this, I mean a function that does not require unthreading a register, but works directly with a vector state.

**Comment by marcosfrenkel** [comment]
measure does that, you just pass the vector state as the right side argument and selects a level based on the specified probabilities (it squares the vector state before rolling).
