### ISSUE TITLE
Implement the measurement operator in a vector state

### ISSUE THREAD

**Issue by nunezco2** [nunezco2/quAPL#3]
For the moment, assume we start with a register, and thread it into a vector state.

* Calculate the resulting basis state (0,1) using projectors and adding up probabilities using a roulette wheel
* Renormalize the probabilities of the rest of the vector state after measurement

**Comment by nunezco2** [comment]
Code for the roulette wheel:

 ⍝ Generate a vector of random values with the right number of dimensions (rows)
    rand ← ?(1⌷⍴⍺)⍴0

    ⍝ Use that vector to choose from a 3-roulette based on the stochastic matrix
    ⍝ per dimension.
    roulette ← 1++/~rand(>⍨⍤0 1)(+\⍺)

**Comment by marcosfrenkel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement the measurement operator in a vector state](https://trello.com/c/FAmcq5vW/29-implement-the-measurement-operator-in-a-vector-state)
